mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\_DEV"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\_\DeployedItems.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\_DEV\DeployedItems.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\A\CommerceServer.Core.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\CommerceServer.Core.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\A\I\R\Reference.Storefront.Catalog.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront\Reference.Storefront.Catalog.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\A\I\R\Reference.Storefront.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront\Reference.Storefront.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\A\I\R\Reference.Storefront.Customer.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront\Reference.Storefront.Customer.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\A\I\R\Reference.Storefront.Index.Lucene.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront\Reference.Storefront.Index.Lucene.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\A\I\R\Reference.Storefront.Index.Solr.config.example" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront\Reference.Storefront.Index.Solr.config.example"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\A\I\R\Reference.Storefront.Orders.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront\Reference.Storefront.Orders.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\A\I\R\Sitecore.ItemWebApi.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Reference.Storefront\Sitecore.ItemWebApi.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\b\AntiXssLibrary.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\AntiXssLibrary.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\b\Castle.Core.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Castle.Core.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\b\Castle.Windsor.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Castle.Windsor.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\b\Sitecore.Reference.Storefront.Powered.by.SitecoreCommerce.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Sitecore.Reference.Storefront.Powered.by.SitecoreCommerce.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\b\WebActivatorEx.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\WebActivatorEx.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\Default.aspx" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Default.aspx"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\favicon.ico" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\favicon.ico"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\MergeFiles"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\M\Merge.Commerce.Storefront.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\MergeFiles\Merge.Commerce.Storefront.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\MergeFiles\Views"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\M\V\Merge.web.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\MergeFiles\Views\Merge.web.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\packages.custom.config.disabled1" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\packages.custom.config.disabled1"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\packages.merged.config.disabled1" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\packages.merged.config.disabled1"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\packages.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\packages.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\C\CastleWinsor_Apache.txt" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights\CastleWinsor_Apache.txt"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\C\Knockout.Validation_MIT.txt" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights\Knockout.Validation_MIT.txt"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\C\Microsoft.AspNet.Mvc_rtw_enu.htm" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights\Microsoft.AspNet.Mvc_rtw_enu.htm"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\C\Microsoft.AspNet.Razor_rtw_enu.htm" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights\Microsoft.AspNet.Razor_rtw_enu.htm"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\C\Microsoft.AspNet.WebApi_rtw_enu.htm" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights\Microsoft.AspNet.WebApi_rtw_enu.htm"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\C\Microsoft.AspNet.WebPages_rtw_enu.htm" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights\Microsoft.AspNet.WebPages_rtw_enu.htm"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\C\Microsoft.Web.Infrastructure-eula.htm" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights\Microsoft.Web.Infrastructure-eula.htm"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\C\Newtonsoft.Json_MIT.txt" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights\Newtonsoft.Json_MIT.txt"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\C\WebActivatorEx_MSPL.txt" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Sitecore\Copyrights\WebActivatorEx_MSPL.txt"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\SitecoreCommerce\Data\Catalog"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\D\C\Catalog.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\SitecoreCommerce\Data\Catalog\Catalog.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\SitecoreCommerce\Data\Inventory"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\D\I\Inventory.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\SitecoreCommerce\Data\Inventory\Inventory.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\SitecoreCommerce\Data\Profiles"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\S\D\P\Profiles.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\SitecoreCommerce\Data\Profiles\Profiles.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\Solr_Schema.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Solr_Schema.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Storefront\Account"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\V\S\A\MyOrder.cshtml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Storefront\Account\MyOrder.cshtml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Storefront\Account"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\V\S\A\MyOrders.cshtml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Storefront\Account\MyOrders.cshtml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Storefront\Catalog"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\V\S\C\ProductInformation.cshtml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Storefront\Catalog\ProductInformation.cshtml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Storefront\Checkout"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1341469\transactions\V\S\C\_Billing.cshtml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Storefront\Checkout\_Billing.cshtml"
