mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\_DEV"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\_\DeployedItems.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\_DEV\DeployedItems.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\A\I\Sitecore.Commerce.UX.CustomerOrderManager.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Sitecore.Commerce.UX.CustomerOrderManager.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\Microsoft.Threading.Tasks.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Threading.Tasks.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\Microsoft.Threading.Tasks.Extensions.Desktop.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Threading.Tasks.Extensions.Desktop.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\Microsoft.Threading.Tasks.Extensions.Desktop.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Threading.Tasks.Extensions.Desktop.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\Microsoft.Threading.Tasks.Extensions.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Threading.Tasks.Extensions.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\Microsoft.Threading.Tasks.Extensions.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Threading.Tasks.Extensions.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\Microsoft.Threading.Tasks.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Threading.Tasks.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\Simple.OData.Client.Net40.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Simple.OData.Client.Net40.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\Simple.OData.Client.Net40.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Simple.OData.Client.Net40.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\Sitecore.Commerce.UX.CustomerOrderManager.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Sitecore.Commerce.UX.CustomerOrderManager.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\System.Net.Http.Extensions.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\System.Net.Http.Extensions.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\System.Net.Http.Extensions.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\System.Net.Http.Extensions.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\System.Net.Http.Primitives.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\System.Net.Http.Primitives.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\b\System.Net.Http.Primitives.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\System.Net.Http.Primitives.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\shell\client\Applications\CustomerOrderManager\Assets\Icons\48x48"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\s\s\c\A\C\A\I\4\CustomerOrderManagement.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\shell\client\Applications\CustomerOrderManager\Assets\Icons\48x48\CustomerOrderManagement.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\shell\client\Applications\CustomerOrderManager\Assets\Styles"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\s\s\c\A\C\A\S\Styles.css" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\shell\client\Applications\CustomerOrderManager\Assets\Styles\Styles.css"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\shell\client\Applications\CustomerOrderManager\Customer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\s\s\c\A\C\C\Customer.js" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\shell\client\Applications\CustomerOrderManager\Customer\Customer.js"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\shell\client\Applications\CustomerOrderManager\Order"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\s\s\c\A\C\O\Order.js" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\shell\client\Applications\CustomerOrderManager\Order\Order.js"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\shell\client\Applications\CustomerOrderManager\Search"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\s\s\c\A\C\S\Search.js" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\shell\client\Applications\CustomerOrderManager\Search\Search.js"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Order"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\V\O\OrderDetails.cshtml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Order\OrderDetails.cshtml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Order"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\V\O\OrderPreview.cshtml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Order\OrderPreview.cshtml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Profile"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\V\P\CustomerDetails.cshtml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Profile\CustomerDetails.cshtml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Profile"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T133000551\transactions\V\P\CustomerPreview.cshtml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Views\Profile\CustomerPreview.cshtml"
