mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\.gitignore" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\.gitignore"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\_DEV"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\_\DeployedItems.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\_DEV\DeployedItems.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\CommerceServer.Core.config.example" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\CommerceServer.Core.config.example"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.Catalog.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.Catalog.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.Connectors.Carts.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.Connectors.Carts.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.Connectors.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.Connectors.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.Connectors.Inventory.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.Connectors.Inventory.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.Connectors.Orders.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.Connectors.Orders.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.ContentSearch.Common.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.ContentSearch.Common.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.ContentSearch.Lucene.DefaultIndexConfiguration.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.ContentSearch.Lucene.DefaultIndexConfiguration.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.ContentSearch.Lucene.Index.Master.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.ContentSearch.Lucene.Index.Master.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.ContentSearch.Lucene.Index.Web.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.ContentSearch.Lucene.Index.Web.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.ContentSearch.Solr.DefaultIndexConfiguration.config.example" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.ContentSearch.Solr.DefaultIndexConfiguration.config.example"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.ContentSearch.Solr.Index.Master.config.example" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.ContentSearch.Solr.Index.Master.config.example"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.ContentSearch.Solr.Index.Web.config.example" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.ContentSearch.Solr.Index.Web.config.example"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.ContentSearch.Solr.Schema.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.ContentSearch.Solr.Schema.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.Customers.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.Customers.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.Processing.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.Processing.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.Profiles.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.Profiles.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.SwitchMasterToWeb.config.disabled" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\CommerceServer\CommerceServer.SwitchMasterToWeb.config.disabled"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Coveo_Commerce"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.ContentSearch.Coveo.Index.Master.config.disabled" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Coveo_Commerce\CommerceServer.ContentSearch.Coveo.Index.Master.config.disabled"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Coveo_Commerce"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.ContentSearch.Coveo.Index.Web.config.disabled" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Coveo_Commerce\CommerceServer.ContentSearch.Coveo.Index.Web.config.disabled"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Coveo_Commerce"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\A\I\C\CommerceServer.Coveo.SearchProvider.Custom.config.disabled" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\App_Config\Include\Coveo_Commerce\CommerceServer.Coveo.SearchProvider.Custom.config.disabled"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\b\HedgehogDevelopment.SitecoreProject.PackageInstallPostProcessor.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\HedgehogDevelopment.SitecoreProject.PackageInstallPostProcessor.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\b\Microsoft.Practices.EnterpriseLibrary.Caching.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Practices.EnterpriseLibrary.Caching.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\b\Microsoft.Practices.EnterpriseLibrary.Caching.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Practices.EnterpriseLibrary.Caching.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\b\Microsoft.Practices.EnterpriseLibrary.Common.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Practices.EnterpriseLibrary.Common.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\b\Microsoft.Practices.EnterpriseLibrary.Common.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Practices.EnterpriseLibrary.Common.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\b\Microsoft.Practices.ServiceLocation.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Practices.ServiceLocation.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\b\Microsoft.Practices.Unity.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Practices.Unity.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\b\Microsoft.Practices.Unity.Interception.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Microsoft.Practices.Unity.Interception.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\b\Sitecore.Commerce.Connect.CommerceServer.dll" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Sitecore.Commerce.Connect.CommerceServer.dll"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\b\Sitecore.Commerce.Connect.CommerceServer.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\bin\Sitecore.Commerce.Connect.CommerceServer.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\brand.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\brand.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\brandmust.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\brandmust.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\brandnot.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\brandnot.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\brandshould.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\brandshould.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\commercesearchitemtype.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\commercesearchitemtype.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\commercesearchitemtypemust.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\commercesearchitemtypemust.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\commercesearchitemtypenot.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\commercesearchitemtypenot.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\commercesearchitemtypeshould.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\commercesearchitemtypeshould.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\definitionname.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\definitionname.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\definitionnamemust.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\definitionnamemust.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\definitionnamenot.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\definitionnamenot.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\definitionnameshould.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\definitionnameshould.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\onsale.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\onsale.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\onsalemust.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\onsalemust.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\onsalenot.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\onsalenot.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\onsaleshould.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\onsaleshould.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\rating.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\rating.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\ratingmust.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\ratingmust.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\ratingnot.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\ratingnot.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\B\i\ratingshould.png" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Buckets\images\ratingshould.png"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\Caching.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Caching.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\layouts\Commerce"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\l\C\CommerceAppLayout.aspx" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\layouts\Commerce\CommerceAppLayout.aspx"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\MergeFiles"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\M\Merge.CommerceServer.config" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\MergeFiles\Merge.CommerceServer.config"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\OrderObjectMappings.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\OrderObjectMappings.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\OrderPipelineMappings.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\OrderPipelineMappings.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\p\Advertising.PCF" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines\Advertising.PCF"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\p\basket.pcf" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines\basket.pcf"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\p\checkout.pcf" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines\checkout.pcf"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\p\CreditCard.pcf" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines\CreditCard.pcf"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\p\Discounts.PCF" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines\Discounts.PCF"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\p\product.pcf" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines\product.pcf"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\p\RecordEvent.pcf" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines\RecordEvent.pcf"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\p\recvpo.pcf" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines\recvpo.pcf"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\p\total.pcf" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\pipelines\total.pcf"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\Shell\Applications\Dialogs\Publish"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\s\S\A\D\P\Publish.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\sitecore\Shell\Applications\Dialogs\Publish\Publish.xml"
mkdir "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Temp\CommerceServerIntegration"
copy /y "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\temp\__Upgrade\Upgrade_20170616T1246225\transactions\T\C\de-DE.xml" "C:\Projects\Ecommerce8.2.1Update1\cf.reference.storefront821.com\Website\Temp\CommerceServerIntegration\de-DE.xml"
